In [26]:
import pandas as pd

In [27]:
messages = pd.read_csv('D:/AI_ML/Expert-Generative-AI-and-Agenetic-Ai-developer/NLP/spam_dataset/spam.csv', encoding='latin1')

In [28]:
messages.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

## Data Cleaning and Preprocessing

In [29]:
messages=messages.iloc[:, :2]
messages.columns=['label', 'message']
messages.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [30]:
messages.shape

(5572, 2)

In [31]:
import re # Import regular expression 
import nltk

In [32]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [33]:
corpus= []

for i in range(0, len(messages)):
    review=re.sub('[^a-zA-z]', ' ', messages['message'][i])
    review=review.lower()
    review=review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review= ' '.join(review)
    corpus.append(review)

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
# For binary bag of words, enable binary=True 
cv=CountVectorizer(max_features=2500, binary=True)

In [35]:
X=cv.fit_transform(corpus).toarray()

In [36]:
X.shape

(5572, 2500)

In [37]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 2500))

## N Gram BOW implementation

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
# For binary bag of words, enable binary=True 
cv=CountVectorizer(max_features=200, binary=True, ngram_range=(1,2))

In [42]:
Y=cv.fit_transform(corpus).toarray()

In [43]:
Y

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 200))

In [46]:
cv.vocabulary_

{'go': np.int64(50),
 'great': np.int64(54),
 'got': np.int64(53),
 'wat': np.int64(183),
 'ok': np.int64(116),
 'free': np.int64(46),
 'win': np.int64(189),
 'st': np.int64(152),
 'may': np.int64(93),
 'text': np.int64(161),
 'txt': np.int64(174),
 'dun': np.int64(36),
 'say': np.int64(137),
 'alreadi': np.int64(0),
 'think': np.int64(164),
 'live': np.int64(82),
 'around': np.int64(5),
 'hey': np.int64(64),
 'week': np.int64(186),
 'word': np.int64(191),
 'back': np.int64(9),
 'like': np.int64(80),
 'still': np.int64(154),
 'send': np.int64(139),
 'even': np.int64(39),
 'per': np.int64(119),
 'friend': np.int64(47),
 'custom': np.int64(30),
 'prize': np.int64(131),
 'claim': np.int64(21),
 'call': np.int64(13),
 'hour': np.int64(69),
 'mobil': np.int64(100),
 'month': np.int64(102),
 'co': np.int64(22),
 'gonna': np.int64(51),
 'home': np.int64(67),
 'soon': np.int64(149),
 'want': np.int64(182),
 'talk': np.int64(159),
 'stuff': np.int64(156),
 'tonight': np.int64(172),
 'today': np.int64(168),
 'cash': np.int64(18),
 'cost': np.int64(28),
 'day': np.int64(32),
 'repli': np.int64(134),
 'urgent': np.int64(177),
 'www': np.int64(194),
 'right': np.int64(135),
 'thank': np.int64(162),
 'take': np.int64(158),
 'help': np.int64(63),
 'time': np.int64(167),
 'use': np.int64(179),
 'next': np.int64(109),
 'messag': np.int64(96),
 'com': np.int64(25),
 'oh': np.int64(115),
 'watch': np.int64(184),
 'name': np.int64(106),
 'ye': np.int64(196),
 'make': np.int64(90),
 'fine': np.int64(43),
 'way': np.int64(185),
 'feel': np.int64(41),
 'dont': np.int64(35),
 'miss': np.int64(99),
 'ur': np.int64(176),
 'tri': np.int64(173),
 'first': np.int64(45),
 'da': np.int64(31),
 'finish': np.int64(44),
 'lor': np.int64(85),
 'meet': np.int64(95),
 'realli': np.int64(133),
 'get': np.int64(48),
 'know': np.int64(73),
 'lol': np.int64(83),
 'alway': np.int64(2),
 'love': np.int64(87),
 'amp': np.int64(3),
 'car': np.int64(16),
 'let': np.int64(78),
 'work': np.int64(192),
 'wait': np.int64(180),
 'sure': np.int64(157),
 'us': np.int64(178),
 'yeah': np.int64(197),
 'tell': np.int64(160),
 'anyth': np.int64(4),
 'uk': np.int64(175),
 'pleas': np.int64(127),
 'look': np.int64(84),
 'msg': np.int64(104),
 'done': np.int64(34),
 'see': np.int64(138),
 'pl': np.int64(123),
 'need': np.int64(107),
 'sm': np.int64(145),
 'nokia': np.int64(112),
 'tomorrow': np.int64(170),
 'pleas call': np.int64(128),
 'hope': np.int64(68),
 'man': np.int64(91),
 'well': np.int64(187),
 'lt': np.int64(88),
 'gt': np.int64(55),
 'lt gt': np.int64(89),
 'could': np.int64(29),
 'ask': np.int64(6),
 'morn': np.int64(103),
 'place': np.int64(124),
 'thought': np.int64(166),
 'best': np.int64(10),
 'happi': np.int64(61),
 'sorri': np.int64(150),
 'give': np.int64(49),
 'offer': np.int64(114),
 'new': np.int64(108),
 'play': np.int64(126),
 'end': np.int64(37),
 'find': np.int64(42),
 'year': np.int64(198),
 'special': np.int64(151),
 'pm': np.int64(129),
 'later': np.int64(76),
 'call later': np.int64(14),
 'reach': np.int64(132),
 'pick': np.int64(122),
 'good': np.int64(52),
 'check': np.int64(20),
 'come': np.int64(26),
 'said': np.int64(136),
 'nice': np.int64(110),
 'award': np.int64(7),
 'money': np.int64(101),
 'hi': np.int64(65),
 'babe': np.int64(8),
 'im': np.int64(70),
 'someth': np.int64(148),
 'peopl': np.int64(118),
 'much': np.int64(105),
 'job': np.int64(71),
 'stop': np.int64(155),
 'one': np.int64(117),
 'start': np.int64(153),
 'night': np.int64(111),
 'late': np.int64(75),
 'mean': np.int64(94),
 'smile': np.int64(146),
 'someon': np.int64(147),
 'servic': np.int64(141),
 'guarante': np.int64(56),
 'plan': np.int64(125),
 'buy': np.int64(12),
 'show': np.int64(143),
 'collect': np.int64(24),
 'yet': np.int64(199),
 'life': np.int64(79),
 'lot': np.int64(86),
 'dear': np.int64(33),
 'wish': np.int64(190),
 'would': np.int64(193),
 'thing': np.int64(163),
 'contact': np.int64(27),
 'last': np.int64(74),
 'ppm': np.int64(130),
 'haha': np.int64(59),
 'happen': np.int64(60),
 'went': np.int64(188),
 'holiday': np.int64(66),
 'min': np.int64(97),
 'box': np.int64(11),
 'number': np.int64(113),
 'sent': np.int64(140),
 'chat': np.int64(19),
 'person': np.int64(120),
 'heart': np.int64(62),
 'gud': np.int64(57),
 'ya': np.int64(195),
 'thk': np.int64(165),
 'leav': np.int64(77),
 'keep': np.int64(72),
 'also': np.int64(1),
 'cant': np.int64(15),
 'guy': np.int64(58),
 'minut': np.int64(98),
 'co uk': np.int64(23),
 'everi': np.int64(40),
 'sleep': np.int64(144),
 'shop': np.int64(142),
 'told': np.int64(169),
 'care': np.int64(17),
 'phone': np.int64(121),
 'tone': np.int64(171),
 'line': np.int64(81),
 'enjoy': np.int64(38),
 'mani': np.int64(92),
 'wan': np.int64(181)}