In [5]:
import pandas as pd

In [6]:
messages = pd.read_csv('D:/AI_ML/Expert-Generative-AI-and-Agenetic-Ai-developer/NLP/spam_dataset/spam.csv', encoding='latin1')

In [7]:
messages.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

## Data Cleaning and Preprocessing

In [8]:
messages=messages.iloc[:, :2]
messages.columns=['label', 'message']
messages.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
messages.shape

(5572, 2)

In [10]:
import re # Import regular expression 
import nltk

In [11]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [12]:
corpus= []

for i in range(0, len(messages)):
    review=re.sub('[^a-zA-z]', ' ', messages['message'][i])
    review=review.lower()
    review=review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review= ' '.join(review)
    corpus.append(review)

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
# For binary bag of words, enable binary=True 
cv=CountVectorizer(max_features=2500, binary=True)

In [20]:
X=cv.fit_transform(corpus).toarray()

In [21]:
X.shape

(5572, 2500)

In [22]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 2500))